<?xml version="1.0" encoding="ISO-8859-1"?>
<definitions xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="PhpSoap" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="PhpSoap">
<types>
<xsd:schema targetNamespace="PhpSoap"
>
 <xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/" />
 <xsd:import namespace="http://schemas.xmlsoap.org/wsdl/" />
</xsd:schema>
</types>
<message name="comprobarPalindroma">
  <part name="name" type="xsd:string" /></message>
<message name="comprobarPalindromaResponse">
  <part name="return" type="xsd:string" /></message>
<portType name="ServicePhpPortType">
  <operation name="comprobarPalindroma">
    <input message="tns:comprobarPalindroma"/>
    <output message="tns:comprobarPalindromaResponse"/>
  </operation>
</portType>
<binding name="ServicePhpBinding" type="tns:ServicePhpPortType">
  <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
  <operation name="comprobarPalindroma">
    <soap:operation soapAction="http://localhost/soap/ServicePhp.php/comprobarPalindroma" style="rpc"/>
    <input><soap:body use="literal" namespace="PhpSoap"/></input>
    <output><soap:body use="literal" namespace="PhpSoap"/></output>
  </operation>
</binding>
<service name="ServicePhp">
  <port name="ServicePhpPort" binding="tns:ServicePhpBinding">
    <soap:address location="http://localhost/soap/ServicePhp.php"/>
  </port>
</service>
</definitions>