//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteNETS.WSOperaciones {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="WSOperaciones.WSOperations")]
    public interface WSOperations {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSOperations/loginRequest", ReplyAction="http://ws/WSOperations/loginResponse")]
        ClienteNETS.WSOperaciones.loginResponse login(ClienteNETS.WSOperaciones.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSOperations/loginRequest", ReplyAction="http://ws/WSOperations/loginResponse")]
        System.Threading.Tasks.Task<ClienteNETS.WSOperaciones.loginResponse> loginAsync(ClienteNETS.WSOperaciones.loginRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSOperations/helloRequest", ReplyAction="http://ws/WSOperations/helloResponse")]
        ClienteNETS.WSOperaciones.helloResponse hello(ClienteNETS.WSOperaciones.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSOperations/helloRequest", ReplyAction="http://ws/WSOperations/helloResponse")]
        System.Threading.Tasks.Task<ClienteNETS.WSOperaciones.helloResponse> helloAsync(ClienteNETS.WSOperaciones.helloRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://ws/).
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSOperations/procesarPagoRequest", ReplyAction="http://ws/WSOperations/procesarPagoResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteNETS.WSOperaciones.procesarPagoResponse procesarPago(ClienteNETS.WSOperaciones.procesarPagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSOperations/procesarPagoRequest", ReplyAction="http://ws/WSOperations/procesarPagoResponse")]
        System.Threading.Tasks.Task<ClienteNETS.WSOperaciones.procesarPagoResponse> procesarPagoAsync(ClienteNETS.WSOperaciones.procesarPagoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="http://ws/", Order=0)]
        public ClienteNETS.WSOperaciones.loginRequestBody Body;
        
        public loginRequest() {
        }
        
        public loginRequest(ClienteNETS.WSOperaciones.loginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class loginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contrasena;
        
        public loginRequestBody() {
        }
        
        public loginRequestBody(string usuario, string contrasena) {
            this.usuario = usuario;
            this.contrasena = contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="http://ws/", Order=0)]
        public ClienteNETS.WSOperaciones.loginResponseBody Body;
        
        public loginResponse() {
        }
        
        public loginResponse(ClienteNETS.WSOperaciones.loginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class loginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public loginResponseBody() {
        }
        
        public loginResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hello", Namespace="http://ws/", Order=0)]
        public ClienteNETS.WSOperaciones.helloRequestBody Body;
        
        public helloRequest() {
        }
        
        public helloRequest(ClienteNETS.WSOperaciones.helloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public helloRequestBody() {
        }
        
        public helloRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloResponse", Namespace="http://ws/", Order=0)]
        public ClienteNETS.WSOperaciones.helloResponseBody Body;
        
        public helloResponse() {
        }
        
        public helloResponse(ClienteNETS.WSOperaciones.helloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public helloResponseBody() {
        }
        
        public helloResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="procesarPago", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class procesarPagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int total;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int pago;
        
        public procesarPagoRequest() {
        }
        
        public procesarPagoRequest(int total, int pago) {
            this.total = total;
            this.pago = pago;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="procesarPagoResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class procesarPagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public procesarPagoResponse() {
        }
        
        public procesarPagoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSOperationsChannel : ClienteNETS.WSOperaciones.WSOperations, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSOperationsClient : System.ServiceModel.ClientBase<ClienteNETS.WSOperaciones.WSOperations>, ClienteNETS.WSOperaciones.WSOperations {
        
        public WSOperationsClient() {
        }
        
        public WSOperationsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSOperationsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSOperationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSOperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteNETS.WSOperaciones.loginResponse ClienteNETS.WSOperaciones.WSOperations.login(ClienteNETS.WSOperaciones.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public bool login(string usuario, string contrasena) {
            ClienteNETS.WSOperaciones.loginRequest inValue = new ClienteNETS.WSOperaciones.loginRequest();
            inValue.Body = new ClienteNETS.WSOperaciones.loginRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contrasena = contrasena;
            ClienteNETS.WSOperaciones.loginResponse retVal = ((ClienteNETS.WSOperaciones.WSOperations)(this)).login(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteNETS.WSOperaciones.loginResponse> ClienteNETS.WSOperaciones.WSOperations.loginAsync(ClienteNETS.WSOperaciones.loginRequest request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteNETS.WSOperaciones.loginResponse> loginAsync(string usuario, string contrasena) {
            ClienteNETS.WSOperaciones.loginRequest inValue = new ClienteNETS.WSOperaciones.loginRequest();
            inValue.Body = new ClienteNETS.WSOperaciones.loginRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contrasena = contrasena;
            return ((ClienteNETS.WSOperaciones.WSOperations)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteNETS.WSOperaciones.helloResponse ClienteNETS.WSOperaciones.WSOperations.hello(ClienteNETS.WSOperaciones.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            ClienteNETS.WSOperaciones.helloRequest inValue = new ClienteNETS.WSOperaciones.helloRequest();
            inValue.Body = new ClienteNETS.WSOperaciones.helloRequestBody();
            inValue.Body.name = name;
            ClienteNETS.WSOperaciones.helloResponse retVal = ((ClienteNETS.WSOperaciones.WSOperations)(this)).hello(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteNETS.WSOperaciones.helloResponse> ClienteNETS.WSOperaciones.WSOperations.helloAsync(ClienteNETS.WSOperaciones.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteNETS.WSOperaciones.helloResponse> helloAsync(string name) {
            ClienteNETS.WSOperaciones.helloRequest inValue = new ClienteNETS.WSOperaciones.helloRequest();
            inValue.Body = new ClienteNETS.WSOperaciones.helloRequestBody();
            inValue.Body.name = name;
            return ((ClienteNETS.WSOperaciones.WSOperations)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteNETS.WSOperaciones.procesarPagoResponse ClienteNETS.WSOperaciones.WSOperations.procesarPago(ClienteNETS.WSOperaciones.procesarPagoRequest request) {
            return base.Channel.procesarPago(request);
        }
        
        public int procesarPago(int total, int pago) {
            ClienteNETS.WSOperaciones.procesarPagoRequest inValue = new ClienteNETS.WSOperaciones.procesarPagoRequest();
            inValue.total = total;
            inValue.pago = pago;
            ClienteNETS.WSOperaciones.procesarPagoResponse retVal = ((ClienteNETS.WSOperaciones.WSOperations)(this)).procesarPago(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteNETS.WSOperaciones.procesarPagoResponse> ClienteNETS.WSOperaciones.WSOperations.procesarPagoAsync(ClienteNETS.WSOperaciones.procesarPagoRequest request) {
            return base.Channel.procesarPagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteNETS.WSOperaciones.procesarPagoResponse> procesarPagoAsync(int total, int pago) {
            ClienteNETS.WSOperaciones.procesarPagoRequest inValue = new ClienteNETS.WSOperaciones.procesarPagoRequest();
            inValue.total = total;
            inValue.pago = pago;
            return ((ClienteNETS.WSOperaciones.WSOperations)(this)).procesarPagoAsync(inValue);
        }
    }
}
